module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Expect
import Html
import SimpleIcons
import Test


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Html.Html msg
                            unused =
                                SimpleIcons.elm |> SimpleIcons.toHtml []
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        let
                            unused : Html.Html msg
                            unused =
                                SimpleIcons.svg
                                    |> SimpleIcons.withColor "#FF00FF"
                                    |> SimpleIcons.withSize "50px"
                                    |> SimpleIcons.toHtml []
                        in
                        Expect.pass
                    )
                ]
            ]
        , Test.describe
            "SimpleIcons"
            [ Test.describe
                "toHtml"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Html.Html msg
                                unused =
                                    SimpleIcons.elm |> SimpleIcons.toHtml []
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "withColor"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : SimpleIcons.Icon
                                unused =
                                    SimpleIcons.elm
                                        |> SimpleIcons.withColor "#000000"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "withInheritedTextColor"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : SimpleIcons.Icon
                                unused =
                                    SimpleIcons.elm
                                        |> SimpleIcons.withInheritedTextColor
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "withNoTitle"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : SimpleIcons.Icon
                                unused =
                                    SimpleIcons.elm |> SimpleIcons.withNoTitle
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "withSize"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : SimpleIcons.Icon
                                unused =
                                    SimpleIcons.elm
                                        |> SimpleIcons.withSize "20px"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "withTitle"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : SimpleIcons.Icon
                                unused =
                                    SimpleIcons.elm
                                        |> SimpleIcons.withTitle
                                            "Great functional language!"
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        ]
